# create your drupal and postgres config here, based off the last assignment


services:
  drupal-service: 
    build:
      context: .
      dockerfile: drupal.Dockerfile

    image: custom-drupal 
    ports:
      - "8080:80"

    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  mariadb-service:
    image: mariadb:10.6

    environment:
      - MARIADB_USER=drupal
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=mariadb
    volumes:
      - drupal-data:/var/lib/mysql

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: 